from app.domain.models.operating import (
    Connector,
    DashboardOverview,
    Decision,
    Evaluation,
    Report,
    Risk,
    SyncRun,
    User,
    WorkItem,
)

USERS = [
    User(id="u-founder", name="Ananya Rao", email="founder@sprintpilot.ai", role="founder", title="Founder / CEO"),
    User(id="u-pm", name="Maya Menon", email="pm@sprintpilot.ai", role="product_manager", title="Product Manager"),
    User(id="u-em", name="Dev Shah", email="em@sprintpilot.ai", role="engineering_manager", title="Engineering Manager"),
    User(id="u-eng", name="Rahul Iyer", email="engineer@sprintpilot.ai", role="engineer", title="Backend Engineer"),
    User(id="u-viewer", name="Nora Lee", email="viewer@sprintpilot.ai", role="viewer", title="Viewer"),
]

WORK_ITEMS = [
    WorkItem(
        id="wi-1",
        external_id="PAY-231",
        title="Implement Stripe payment gateway",
        description="Payment intent creation, webhook verification, and retry-safe order updates.",
        status="In Progress",
        priority="High",
        assignee="Rahul",
        reporter="Maya",
        sprint="Sprint 14",
        epic="Checkout Modernization",
        labels=["payments", "checkout", "launch"],
        due_date="2026-06-14",
        source="Jira",
        source_url="https://jira.example.com/browse/PAY-231",
        risk_level="medium",
        blocker_reason="Retry-safe order update behavior still needs staging validation.",
        stale_score=32,
        business_impact="Checkout launch readiness depends on reliable payment processing.",
        suggested_next_action="Run one focused staging pass for webhook retries and idempotency.",
        updated_at="2026-06-06",
    ),
    WorkItem(
        id="wi-2",
        external_id="AUTH-118",
        title="Session refresh reliability",
        description="Fix token refresh race condition during long checkout sessions.",
        status="In Review",
        priority="High",
        assignee="Isha",
        reporter="Dev",
        sprint="Sprint 14",
        epic="Checkout Modernization",
        labels=["auth", "checkout"],
        due_date="2026-06-12",
        source="Jira",
        source_url="https://jira.example.com/browse/AUTH-118",
        risk_level="medium",
        blocker_reason=None,
        stale_score=18,
        business_impact="Failed checkout sessions can reduce conversion and delay launch sign-off.",
        suggested_next_action="Review regression tests and merge if staging remains stable.",
        updated_at="2026-06-05",
    ),
    WorkItem(
        id="wi-3",
        external_id="OBS-042",
        title="Checkout metrics dashboard",
        description="Payment funnel metrics, webhook failure alerts, and latency dashboard.",
        status="Done",
        priority="Medium",
        assignee="Dev",
        reporter="Maya",
        sprint="Sprint 14",
        epic="Launch Readiness",
        labels=["metrics", "alerts"],
        due_date="2026-06-06",
        source="Jira",
        source_url="https://jira.example.com/browse/OBS-042",
        risk_level="low",
        blocker_reason=None,
        stale_score=4,
        business_impact="Improves incident response during launch week.",
        suggested_next_action="Use dashboard during launch readiness review.",
        updated_at="2026-06-05",
    ),
    WorkItem(
        id="wi-4",
        external_id="REL-077",
        title="Release notes automation",
        description="Generate release notes from merged tickets and sprint summaries.",
        status="In Progress",
        priority="Medium",
        assignee="Nora",
        reporter="Maya",
        sprint="Sprint 14",
        epic="Stakeholder Comms",
        labels=["release-notes", "reporting"],
        due_date="2026-06-13",
        source="ClickUp",
        source_url="https://clickup.example.com/t/REL-077",
        risk_level="low",
        blocker_reason="Citation cleanup required before external use.",
        stale_score=41,
        business_impact="Leadership updates need source-backed summaries.",
        suggested_next_action="Clean citation formatting and validate one generated release draft.",
        updated_at="2026-06-04",
    ),
    WorkItem(
        id="wi-5",
        external_id="PAY-245",
        title="Refund processing support",
        description="Implement refund API and admin support workflow.",
        status="Todo",
        priority="Medium",
        assignee="Maya",
        reporter="Priya",
        sprint="Sprint 15",
        epic="Payments Platform",
        labels=["refunds", "admin"],
        due_date="2026-06-20",
        source="Jira",
        source_url="https://jira.example.com/browse/PAY-245",
        risk_level="low",
        blocker_reason="Depends on PAY-231 stabilization.",
        stale_score=15,
        business_impact="Important for support readiness after checkout launch.",
        suggested_next_action="Start implementation after payment gateway sign-off.",
        updated_at="2026-06-03",
    ),
]

RISKS = [
    Risk(
        id="risk-1",
        title="Payment retry behavior not fully validated",
        level="medium",
        owner="Rahul",
        status="Open",
        business_impact="Can delay checkout launch sign-off.",
        evidence=["PAY-231", "payments Slack update", "Project Phoenix launch criteria"],
        recommended_action="Run one focused staging pass for retry-safe order updates.",
        source_url="https://jira.example.com/browse/PAY-231",
    ),
    Risk(
        id="risk-2",
        title="Auth refresh instability could affect checkout conversion",
        level="medium",
        owner="Isha",
        status="Monitoring",
        business_impact="Long-running checkout sessions may fail if AUTH-118 is delayed.",
        evidence=["AUTH-118", "checkout QA update"],
        recommended_action="Prioritize review and regression coverage before launch review.",
        source_url="https://jira.example.com/browse/AUTH-118",
    ),
    Risk(
        id="risk-3",
        title="Release notes need source citation cleanup",
        level="low",
        owner="Nora",
        status="Open",
        business_impact="External stakeholder updates should not ship without verifiable citations.",
        evidence=["REL-077", "release channel update"],
        recommended_action="Validate one release note draft against source evidence.",
        source_url="https://clickup.example.com/t/REL-077",
    ),
]

DECISIONS = [
    Decision(
        id="decision-1",
        title="Approve checkout launch after final staging pass?",
        owner="Founder / PM",
        due_date="2026-06-13",
        impact_if_delayed="Launch window may slip by one sprint.",
        options=["Launch after staging pass", "Delay until refund support starts", "Launch behind feature flag"],
        source_url="https://jira.example.com/browse/PAY-231",
    ),
    Decision(
        id="decision-2",
        title="Should release notes be internal-only this week?",
        owner="Maya",
        due_date="2026-06-12",
        impact_if_delayed="Customer-facing comms may contain weak source attribution.",
        options=["Internal-only", "External with manual review", "Delay release notes"],
        source_url="https://clickup.example.com/t/REL-077",
    ),
]

REPORTS = [
    Report(
        id="report-founder-weekly",
        type="Weekly Founder Brief",
        title="Checkout launch operating brief",
        summary="Checkout launch is mostly on track, with medium risk until payment retry behavior and auth stability pass final validation.",
        shipped_work=["Checkout metrics dashboard shipped", "Stripe webhook verification passed in staging"],
        blocked_work=["No hard blockers", "PAY-231 still needs retry validation"],
        risks=["Payment retry behavior", "Auth refresh reliability", "Release note citation quality"],
        decisions_needed=["Approve launch after final staging pass", "Decide release note audience"],
        action_items=["Run staging pass", "Review AUTH-118", "Validate release note citations"],
        citations=["PAY-231", "AUTH-118", "OBS-042", "REL-077"],
        confidence_score=91,
        generated_at="2026-06-09T09:00:00Z",
    ),
    Report(
        id="report-pm-sprint",
        type="Product Sprint Update",
        title="Sprint 14 product update",
        summary="Payments and auth remain the critical path. Reporting automation is useful internally but needs polish before external use.",
        shipped_work=["Metrics dashboard", "Webhook verification"],
        blocked_work=["None"],
        risks=["Retry validation", "Auth review"],
        decisions_needed=["Launch readiness sign-off"],
        action_items=["Follow up with Rahul", "Check Isha's review status"],
        citations=["PAY-231", "AUTH-118", "REL-077"],
        confidence_score=88,
        generated_at="2026-06-08T16:30:00Z",
    ),
]

CONNECTORS = [
    Connector(id="jira", name="Jira", status="mock", auth_type="OAuth / API token", last_synced_at="2026-06-09T09:10:00Z", scopes=["read:issues", "read:comments", "read:projects"], env_vars=["JIRA_BASE_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"]),
    Connector(id="slack", name="Slack", status="mock", auth_type="OAuth", last_synced_at="2026-06-09T09:05:00Z", scopes=["search:read", "channels:history"], env_vars=["SLACK_BOT_TOKEN"]),
    Connector(id="github", name="GitHub", status="mock", auth_type="GitHub App", last_synced_at="2026-06-09T08:45:00Z", scopes=["issues:read", "pull_requests:read"], env_vars=["GITHUB_APP_ID", "GITHUB_PRIVATE_KEY"]),
    Connector(id="confluence", name="Confluence", status="not_connected", auth_type="OAuth", scopes=["read:pages"], env_vars=["CONFLUENCE_BASE_URL", "CONFLUENCE_API_TOKEN"]),
    Connector(id="notion", name="Notion", status="not_connected", auth_type="OAuth", scopes=["read:content"], env_vars=["NOTION_TOKEN"]),
    Connector(id="linear", name="Linear", status="not_connected", auth_type="OAuth", scopes=["read:issues"], env_vars=["LINEAR_API_KEY"]),
]

EVALUATIONS = [
    Evaluation(id="eval-1", name="Groundedness", score=94, status="pass", latency_ms=640, token_usage=1700, cost_estimate_usd=0.012),
    Evaluation(id="eval-2", name="Hallucination check", score=96, status="pass", latency_ms=520, token_usage=1200, cost_estimate_usd=0.009),
    Evaluation(id="eval-3", name="Retrieval relevance", score=91, status="pass", latency_ms=430, token_usage=900, cost_estimate_usd=0.006),
    Evaluation(id="eval-4", name="Citation accuracy", score=89, status="warn", latency_ms=580, token_usage=1400, cost_estimate_usd=0.01),
]

ROLE_HEADLINES = {
    "founder": "Mostly on track, but checkout launch needs one final validation pass.",
    "product_manager": "Sprint 14 is moving, with two owner follow-ups and one release-note polish item.",
    "engineering_manager": "No hard blockers, but payment retry validation and auth review remain the delivery risks.",
    "engineer": "Your highest-impact work is PAY-231 validation and closing retry-safe order updates.",
    "viewer": "Checkout launch is mostly on track with medium risk and clear next actions.",
}


def dashboard_for_role(role: str) -> DashboardOverview:
    normalized_role = role if role in ROLE_HEADLINES else "founder"
    return DashboardOverview(
        role=normalized_role,  # type: ignore[arg-type]
        headline=ROLE_HEADLINES[normalized_role],
        sprint_health=83,
        open_risks=len(RISKS),
        blocked_work=0,
        decisions_needed=len(DECISIONS),
        business_impact="Checkout launch remains the highest-priority revenue workflow this sprint.",
        weekly_brief_preview=REPORTS[0].summary,
        suggested_next_actions=[risk.recommended_action for risk in RISKS[:3]],
        latest_changes=[
            "Stripe webhook verification passed in staging",
            "Auth refresh fix moved to review",
            "Checkout metrics became available",
            "Release note citations still need cleanup",
        ],
        owner_workload={"Rahul": 3, "Isha": 2, "Nora": 2, "Maya": 2, "Dev": 1},
    )


def sync_connector(connector_id: str) -> SyncRun:
    known = {connector.id for connector in CONNECTORS}
    return SyncRun(
        id=f"sync-{connector_id}-demo",
        connector_id=connector_id,
        status="completed" if connector_id in known else "error",
        records_synced=18 if connector_id in known else 0,
        error=None if connector_id in known else "Unknown connector",
    )
